name: Always Pass

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-checks:
    name: code-checks
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo "âœ… code-checks init passes" && exit 0
